# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now=True)),
                ('headline', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('writer', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('name', models.CharField(max_length=20)),
                ('articles', models.ManyToManyField(default=None, to='myform.Article')),
            ],
            options={
                'db_table': 'Author',
            },
        ),
    ]
