# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0003_comment_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=30)),
                ('articles', models.ManyToManyField(to='myform.Article')),
            ],
            options={
                'db_table': 'theme',
            },
        ),
    ]
