# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0004_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ManyToManyField(to='myform.Theme'),
        ),
    ]
