# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0005_auto_20170110_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='theme',
            new_name='themes',
        ),
    ]
